# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Gregg Miller
tagline:             'BI Developer'
description:         ''
url:                 https://gr3ggm.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Gregg Miller
  url:               https://gr3ggm.github.io/
  email:             gregg.miller@gmail.com

# Custom vars
version:             1.0.0

# Adding the sitemap gem as per GitHub documentation
gems:
  - jekyll-sitemap
